
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Deploy web servers
      ec2:
        key_name: manu-fedora-t480
        group_id: sg-02a404b9419162add
        instance_type: t2.micro
        image: ami-dd3c0f36
        wait: true
        exact_count: 2
        region: eu-central-1
        instance_tags:
          Name: web
        zone: eu-central-1a
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 20
            delete_on_termination: true
      register: web
    
    - name: Deploy db servers
      ec2:
        key_name: manu-fedora-t480
        group_id: sg-02a404b9419162add
        instance_type: t2.micro
        image: ami-dd3c0f36
        wait: true
        exact_count: 2
        region: eu-central-1
        instance_tags:
          Name: db
        zone: eu-central-1a
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 20
            delete_on_termination: true
      register: db

    - name: Deploy backup servers
      ec2:
        key_name: manu-fedora-t480
        group_id: sg-02a404b9419162add
        instance_type: t2.micro
        image: ami-dd3c0f36
        wait: true
        exact_count: 2
        region: eu-central-1
        instance_tags:
          Name: backup
        zone: eu-central-1a
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 20
            delete_on_termination: true
      register: backup
